[project]
name = 'augurrank-smart-contracts'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[contracts.augur-enroll]
path = 'contracts/augur-enroll.clar'
clarity_version = 3
epoch = 3.1

[contracts.augur-markets]
path = 'contracts/augur-markets.clar'
clarity_version = 3
epoch = 3.1

[contracts.augur-store]
path = 'contracts/augur-store.clar'
clarity_version = 3
epoch = 3.1

[contracts.augur-token]
path = 'contracts/augur-token.clar'
clarity_version = 3
epoch = 3.1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
